config/routes.rb
Rails.application.routes.draw do
  resources :dictionaries
  resources :words
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root :to => 'course#index'
  get 'courses', to: 'course#index', as: 'courses'
  get 'courses/create', to: 'course#create', as: 'courses2'
  get 'courses/:course_id', to: 'lesson#index', as: 'lessons'
  # Course editor
  get 'courses/:course_id/edit', to: 'lesson#edit', as: 'lessons_edit'
  get 'courses/:course_id/:lesson_id/', to: 'content#index', as: 'content'
  get 'courses/:course_id/:lesson_id/edit', to: 'content#edit', as: 'content_edit'
  get 'courses/:course_id/:lesson_id/:element_id', to: 'content#show', as: 'element'
  get 'content/:course_id/', to: 'content#index', as: 'content2'
  get 'content/:course_id/:element_id/', to: 'content#show', as: 'element2'

  # Logowanie
  get 'users/login' => 'users#login'
  post 'users/login' => 'sessions#create'

  # Rejestracja
  get '/users/register' => 'users#register'
  post '/users/register' => 'users#create'

  # Wylogowanie
  get 'users/logout' => 'users#logout'

  # Reviews
  get 'reviews' => 'reviews#index'

  # Words
  post 'content/addtoreviews' => 'content#add_to_reviews'

  # Update lesson sequence
  post 'lesson/sequpdate' => 'lesson#sequence_update'

  # Add new lesson
  post 'lesson/addnewlesson' => 'lesson#add_new_lesson'

  # Add new content
  post 'content/addnewcontent' => 'content#add_new_content'

  # Update content
  patch 'content/updatecontent' => 'content#update_content'

  # Delete content
  delete 'content/deletecontent' => 'content#delete_content'

  # Update content sequence
  post 'content/sequpdate' => 'content#sequence_update'

  # Rename lesson
  patch 'lesson/rename' => 'lesson#rename'

  # Delete lesson
  delete 'lesson/delete' => 'lesson#delete'

  # Dictionary
  get 'dictionary' => 'dictionary#dictionary'
  get 'dictionary/search' => 'dictionary#search'
  post 'dictionary/search' => 'dictionary#search'

  # Writer
  get 'writer' => 'dictionary#writer'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  self.inheritance_column = nil
  attr_accessor :type
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :user
end

app/controllers/dictionary_controller.rb
class DictionaryController < ApplicationController
  before_action :set_dictionary, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /dictionaries or /dictionaries.json
  def index
    @dictionaries = Dictionary.all
  end

  # Search by name
  #
  def search
    @word = params[:word]
    @dictionaries = Dictionary.where(["lang1 = ? and lang2 = ? and status=1 and (word like ? or translation like ?)", "nk", "pl", "%"+@word+"%", "%"+@word+"%"])
    result = ""
    @dictionaries.each do |dictionary|
      result << "<li><h3><b>#{dictionary.word}</b> - #{dictionary.translation}</h3></li>"
    end
    result = "<ul>#{result}</ul>"
    render plain: result
  end

  # GET /dictionaries/1 or /dictionaries/1.json
  def show
  end

  # GET /dictionaries/new
  def new
    @dictionary = Dictionary.new
  end

  # GET /dictionaries/1/edit
  def edit
  end

  # POST /dictionaries or /dictionaries.json
  def create
    @dictionary = Dictionary.new(dictionary_params)

    respond_to do |format|
      if @dictionary.save
        format.html { redirect_to @dictionary, notice: "Dictionary was successfully created." }
        format.json { render :show, status: :created, location: @dictionary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dictionaries/1 or /dictionaries/1.json
  def update
    respond_to do |format|
      if @dictionary.update(dictionary_params)
        format.html { redirect_to @dictionary, notice: "Dictionary was successfully updated." }
        format.json { render :show, status: :ok, location: @dictionary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1 or /dictionaries/1.json
  def destroy
    @dictionary.destroy
    respond_to do |format|
      format.html { redirect_to dictionaries_url, notice: "Dictionary was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # Show dictionary

  def dictionary
    render 'dictionary'
  end

  # Use writer
  def writer
    render 'writer'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dictionary
      @dictionary = Dictionary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dictionary_params
      params.permit(:dictionary).permit(:lang1, :lang2, :word, :translation, :type, :extra, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  $selected_course_id = "1"

  def index

  end

  def register_form
    render 'register'
  end

  def login_form
    render 'login'
  end

  def logout
    session[:user_id] = 0
    redirect_to "/"
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to "/"
    else
      flash[:register_errors] = user.errors.fill_messages
      redirect_to "/users/register"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.where "user_id = #{session[:user_id]}", false
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create

    @word = Word.find_or_create_by(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def word_params
      params.permit(:lang1, :lang2, :word, :translation, :extra)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/dictionary_helper.rb
module DictionaryHelper
end

app/helpers/lesson_helper.rb
module LessonHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/dictionary/_form.html.erb
<%= form_with(model: dictionary) do |form| %>
  <% if dictionary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dictionary.errors.count, "error") %> prohibited this dictionary from being saved:</h2>

      <ul>
        <% dictionary.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lang1 %>
    <%= form.text_field :lang1 %>
  </div>

  <div class="field">
    <%= form.label :lang2 %>
    <%= form.text_field :lang2 %>
  </div>

  <div class="field">
    <%= form.label :word %>
    <%= form.text_field :word %>
  </div>

  <div class="field">
    <%= form.label :translation %>
    <%= form.text_field :translation %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :extra %>
    <%= form.text_field :extra %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dictionary/dictionary.erb
<div class="content-dictionary">
  <br/><h2 id="word" style="text-align: center">Nikkila Dictionary</h2><br/>
  <div class="input-group input-group-lg">
    <input type="text" id="searchBox" class="form-control" aria-label="Label" aria-describedby="inputGroup-sizing-sm">
  </div><br/><br/>
</div>

<div class="result" id="result">
  <ul>
   <% if @dictionaries != nil
        @dictionaries.each do |dictionary| %>
        <li><%=dictionary.word %> - <%=dictionary.translation %></li>
    <% end %>
    <% end %>
  </ul>
</div>

<script type="text/javascript">
    var word = "";
    $("document").ready(function() {
        $("#searchBox").unbind('keyup').keyup(function(event) {
            if (event.keyCode === 13) {
                word = $('#searchBox').val();
                $.ajax({
                    url: '/dictionary/search',
                    type: 'POST',
                    data: {
                        word: word
                    },
                    success: function(r) {
                        $("#result").html(r);
                    }
                });
                return false;
            }
        });
    });
</script>

app/views/dictionary/edit.html.erb
<h1>Editing dictionary data</h1>

<%= render 'form', dictionary: @dictionary %>

<%= link_to 'Show', @dictionary %> |
<%= link_to 'Back', dictionaries_path %>

app/views/dictionary/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dictionary entries</h1>

<table>
  <thead>
    <tr>
      <th>Lang1</th>
      <th>Lang2</th>
      <th>Word</th>
      <th>Translation</th>
      <th>Type</th>
      <th>Extra</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dictionaries.each do |dictionary| %>
      <tr>
        <td><%= dictionary.lang1 %></td>
        <td><%= dictionary.lang2 %></td>
        <td><%= dictionary.word %></td>
        <td><%= dictionary.translation %></td>
        <td><%= dictionary.type %></td>
        <td><%= dictionary.extra %></td>
        <td><%= dictionary.status %></td>
        <td><%= link_to 'Show', dictionary %></td>
        <td><%= link_to 'Edit', edit_dictionary_path(dictionary) %></td>
        <td><%= link_to 'Destroy', dictionary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dictionary', new_dictionary_path %>

app/views/dictionary/new.html.erb
<h1>New dictionary entry</h1>

<%= render 'form', dictionary: @dictionary %>

<%= link_to 'Back', dictionaries_path %>

app/views/dictionary/search.html.erb
<ul>
  <% if @dictionaries != nil
       @dictionaries.each do |dictionary| %>
      <li><%=dictionary.word %> - <%=dictionary.translation %></li>
    <% end %>
  <% end %>
</ul>

app/views/dictionary/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lang1:</strong>
  <%= @dictionary.lang1 %>
</p>

<p>
  <strong>Lang2:</strong>
  <%= @dictionary.lang2 %>
</p>

<p>
  <strong>Word:</strong>
  <%= @dictionary.word %>
</p>

<p>
  <strong>Translation:</strong>
  <%= @dictionary.translation %>
</p>

<p>
  <strong>Type:</strong>
  <%= @dictionary.type %>
</p>

<p>
  <strong>Extra:</strong>
  <%= @dictionary.extra %>
</p>

<p>
  <strong>Status:</strong>
  <%= @dictionary.status %>
</p>

<%= link_to 'Edit', edit_dictionary_path(@dictionary) %> |
<%= link_to 'Back', dictionaries_path %>

app/views/dictionary/writer.erb
<div class="content-dictionary">
  <br/><h2 id="word" style="text-align: center">Nikkila Writer</h2><br/>
  <div class="input-group input-group-lg">
    <textarea id="writeBox" rows="10" class="form-control" aria-label="Label" aria-describedby="inputGroup-sizing-sm"></textarea>
  </div><br/><br/>
</div>

<div class="result" id="result">
  <ul>
   <% if @dictionaries != nil
        @dictionaries.each do |dictionary| %>
        <li><%=dictionary.word %> - <%=dictionary.translation %></li>
    <% end %>
    <% end %>
  </ul>
</div>

<script type="text/javascript">
    var word = "";
    var dictionary = {};
    dictionary['house'] = 'czira';
    dictionary['girl'] = 'mirmila';
    dictionary['boy'] = 'maszira';
    dictionary['beautiful'] = 'sunele';
    dictionary['clever'] = 'minre';
    dictionary['person'] = 'uczna';
    dictionary['I'] = 'An';
    dictionary['You'] = 'Rit';
    dictionary['you'] = 'rit';
    dictionary['he'] = 'lit';
    dictionary['she'] = 'sit';
    dictionary['He'] = 'Lit';
    dictionary['She'] = 'Sit';
    dictionary['sleep'] = 'elsi';
    dictionary['now'] = 'źimda';
    dictionary['today'] = 'asna';
    dictionary['yesterday'] = 'kirla';
    dictionary['tomorrow'] = 'amra';
    dictionary['are'] = 'ima';
    dictionary['is'] = 'ima';
    dictionary['am'] = 'ima';
    dictionary['here'] = 'elsz';
    dictionary['there'] = 'ardz';

    $("document").ready(function() {
        var lastChar = 0;
        $("#writeBox").unbind('keyup').keyup(function(event) {
            console.log(event.keyCode);
            if (event.keyCode === 64 || ( event.keyCode === 50 && lastChar === 16)) {
                word = $('#writeBox').val();
                if(word.indexOf("@") !== -1){
                    wordArray = word.split(" ");
                    lastWord = wordArray.at(-1).trim().slice(0,-1);
                    if(lastWord == ""){
                        lastWord = wordArray.at(-2).trim().slice(0,-1);
                    }
                    if(dictionary.hasOwnProperty(lastWord)){
                        newWord = dictionary[lastWord]
                        word = word.replace(lastWord+"@", newWord);
                        $("#writeBox").val(word);
                        /*
                        if(word.slice(-3,-2) == 'i'){
                            $("#writeBox").val(word.slice(0,-2));
                        } else {
                            $("#writeBox").val(word);
                        }
                        */
                    }
                }
            }
            lastChar = event.keyCode;
        });
    });
</script>