config/routes.rb
Rails.application.routes.draw do
  resources :dictionaries
  resources :words
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root :to => 'course#index'
  get 'courses', to: 'course#index', as: 'courses'
  get 'courses/create', to: 'course#create', as: 'courses2'
  get 'courses/:course_id', to: 'lesson#index', as: 'lessons'
  # Course editor
  get 'courses/:course_id/edit', to: 'lesson#edit', as: 'lessons_edit'
  get 'courses/:course_id/:lesson_id/', to: 'content#index', as: 'content'
  get 'courses/:course_id/:lesson_id/edit', to: 'content#edit', as: 'content_edit'
  get 'courses/:course_id/:lesson_id/:element_id', to: 'content#show', as: 'element'
  get 'content/:course_id/', to: 'content#index', as: 'content2'
  get 'content/:course_id/:element_id/', to: 'content#show', as: 'element2'

  # Logowanie
  get 'users/login' => 'users#login'
  post 'users/login' => 'sessions#create'

  # Rejestracja
  get '/users/register' => 'users#register'
  post '/users/register' => 'users#create'

  # Wylogowanie
  get 'users/logout' => 'users#logout'

  # Reviews
  get 'reviews' => 'reviews#index'

  # Words
  post 'content/addtoreviews' => 'content#add_to_reviews'

  # Update lesson sequence
  post 'lesson/sequpdate' => 'lesson#sequence_update'

  # Add new lesson
  post 'lesson/addnewlesson' => 'lesson#add_new_lesson'

  # Add new content
  post 'content/addnewcontent' => 'content#add_new_content'

  # Update content
  patch 'content/updatecontent' => 'content#update_content'

  # Delete content
  delete 'content/deletecontent' => 'content#delete_content'

  # Update content sequence
  post 'content/sequpdate' => 'content#sequence_update'

  # Rename lesson
  patch 'lesson/rename' => 'lesson#rename'

  # Delete lesson
  delete 'lesson/delete' => 'lesson#delete'

  # Dictionary
  get 'dictionary' => 'dictionary#dictionary'
  get 'dictionary/search' => 'dictionary#search'
  post 'dictionary/search' => 'dictionary#search'

  # Writer
  get 'writer' => 'dictionary#writer'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  self.inheritance_column = nil
  attr_accessor :type
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :user
end

app/controllers/course_controller.rb
class CourseController < ApplicationController

  def index
    if(cookies[:course_id] == nil)
      $selected_course_id = ""
    else
      $selected_course_id = cookies[:course_id]
    end
    # Filter courses or show all courses
    # No param: all courses
    # target_lang param -> filter by target lang
    # instr_lang param -> filter by instr lang
    if params[:target_lang] != nil and params[:instr_lang] != nil
      @courses = Course.where target_lang: params[:target_lang], instr_lang: params[:instr_lang]
    elsif params[:target_lang] != nil
      @courses = Course.where target_lang: params[:target_lang]
    elsif params[:instr_lang] != nil
    @courses = Course.where instr_lang: params[:instr_lang]
    else
      @courses = Course.all
    end
  end

  def create
    @languages = Language.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  $selected_course_id = "1"

  def index

  end

  def register_form
    render 'register'
  end

  def login_form
    render 'login'
  end

  def logout
    session[:user_id] = 0
    redirect_to "/"
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to "/"
    else
      flash[:register_errors] = user.errors.fill_messages
      redirect_to "/users/register"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.where "user_id = #{session[:user_id]}", false
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create

    @word = Word.find_or_create_by(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def word_params
      params.permit(:lang1, :lang2, :word, :translation, :extra)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/dictionary_helper.rb
module DictionaryHelper
end

app/helpers/lesson_helper.rb
module LessonHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/course/create.html.erb
<h2>Create new course</h2>
<form>
  <div class="mb-3">
    <label class="form-label">Course name</label>
    <input id="courseName" type="email" class="form-control" id="courseName" aria-describedby="emailHelp">
  </div>
  <br>
  <label class="form-label">Course language</label>
  <select id="courseLanguage" class="form-select" aria-label="Default select example">
    <% @languages = Language.all %>
    <% @languages.each do |language| %>
      <option value="<%=language.lang_code%>"><%=language.name%></option>
    <% end %>
  </select>
  <br>
  <label class="form-label">Course image</label>

  <div class="custom-file">
    <input type="file" class="custom-file-input" id="exampleInputFile" accept="image/x-png,image/jpeg">
    <label class="custom-file-label" for="exampleInputFile" data-browse="Browse images">Select course image</label>
  </div>
  <br><br>
  <button type="submit" class="btn btn-primary">Create course</button>
</form>

app/views/course/index.html.erb
<div id="courses"></div>
			<!-- Course list -->
<h2>Select course
<% if session[:user_id] == nil || session[:user_id] == 0 %>
	&nbsp;&nbsp;&nbsp;<button type="create-course-button" class="btn btn-info" onclick="location.href='/courses/create';" value="Create course">Create course</button>
<% end %>
</h2>
<% if @courses.size == nil || @courses.size == 0 %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">No courses found!</h4>
    <strong>No courses found for specified language!</strong></strong>
  </div>
  <br/>
<% else %>
<% end %>
			<div class="select-course">
				<% @courses.each do |course| %>
				<div class="card" style="width: 10rem;">
				<%= link_to(image_tag(course.img_url, class:"card-img-top", alt: course.name), "/courses/#{course.id}") %>
				<div class="card-body">
				<h5 class="card-title"><%= course.name %></h5>
				<p class="card-text"><%= course.description %></p>
				</div>
				</div>
				<% end %>
				
</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>User index</title>
</head>
<body>
  <p> something here..</p>

</body>
</html>

app/views/users/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Login</title>
</head>
<body>
<h1>Login</h1>

<% if session[:user_id] == nil || session[:user_id] == 0 %>

<form action="/users/login" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>"><br/>
  E-mail:<br/>
  <input type="email" name="login[email]" placeholder="email"><br/>
  Password:<br/>
  <input type="password" name="login[password]" placeholder="password"><br/>
  <br/>
  <input type="submit" name="submit" class="submit"><br/>
</form>
<br/>

<div class="errors">
  <% if flash[:login_errors] %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">Login failed!</h4>
    <% flash[:login_errors].each do |error| %>
     <strong><%= error %></strong>
    <%end %>
    </div>
  <% end %>

</div>

<% else %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Forbidden</h4>
    <strong>You are already logged in.</strong>
  </div>
<% end %>

</body>
</html>

app/views/users/register.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Registration</title>
</head>

<body>
<h1>Registration</h1>

<% if session[:user_id] == nil || session[:user_id] == 0 %>

  <form action="/users/register" method="POST">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">
    Name:</br>
    <input type="name" name="user[name]" placeholder="name"><br/>
    E-mail:<br/>
    <input type="email" name="user[email]" placeholder="email"><br/>
    Password:<br/>
    <input type="password" name="user[password]" placeholder="password"></br>
    Confirm password:<br/>
    <input type="password" name="user[password_confirmation]" placeholder="password_confirmation"><br>
    <br/>
    <input type="submit" name="submit" class="submit">
  </form>

  <div class="errors">
    <% if flash[:register_errors] %>
      <% flash[:register_errors].each do |error| %>
        <p><%= error %></p>
      <%end %>
    <% end %>
  </div>

<% else %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Forbidden</h4>
    <strong>Multiple accounts are not allowed.</strong>
  </div>
<% end %>

</body>
</html>

app/views/words/_form.html.erb
<%= form_with(model: word) do |form| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
        <% word.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lang1 %>
    <%= form.text_field :lang1 %>
  </div>

  <div class="field">
    <%= form.label :lang2 %>
    <%= form.text_field :lang2 %>
  </div>

  <div class="field">
    <%= form.label :word %>
    <%= form.text_field :word %>
  </div>

  <div class="field">
    <%= form.label :translation %>
    <%= form.text_field :translation %>
  </div>

  <div class="field">
    <%= form.label :extra %>
    <%= form.text_field :extra %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Words</h1>

<table>
  <thead>
    <tr>
      <th>Lang1</th>
      <th>Lang2</th>
      <th>Word</th>
      <th>Translation</th>
      <th>Extra</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.lang1 %></td>
        <td><%= word.lang2 %></td>
        <td><%= word.word %></td>
        <td><%= word.translation %></td>
        <td><%= word.extra %></td>
        <td><%= link_to raw('<i class="fas fa-eye"></i> Show'), word %></td>
        <td><%= link_to raw('<i class="fas fa-edit"></i> Edit'), edit_word_path(word) %></td>
        <td><%= link_to raw('<i class="fas fa-trash"></i> Delete'), word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lang1:</strong>
  <%= @word.lang1 %>
</p>

<p>
  <strong>Lang2:</strong>
  <%= @word.lang2 %>
</p>

<p>
  <strong>Word:</strong>
  <%= @word.word %>
</p>

<p>
  <strong>Translation:</strong>
  <%= @word.translation %>
</p>

<p>
  <strong>Extra:</strong>
  <%= @word.extra %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>